# -*- coding: utf-8 -*-
"""odev1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G1i-TrI9dGAbmW6PpD1NxJ44c7Y0ggdx
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
from google.colab.patches import cv2_imshow



foto=cv2.imread("cicek.png")
renkli_foto = cv2_imshow(foto)

B = foto[:,:,0]
G = foto[:,:,1]
R = foto[:,:,2]


from matplotlib import pyplot as plt
#grileştirme:
imgGray = 0.2989 * R + 0.5870 * G + 0.1140 * B
plt.imshow(imgGray, cmap='gray')
plt.show()




histogram = np.zeros(256)
for i in range(foto.shape[0]):
    for j in range(foto.shape[1]):
        pixel_deg= foto[i, j]
        histogram[pixel_deg] += 1

plt.bar(range(256), histogram)
plt.xlabel("Parlaklık ")
plt.ylabel("Piksel Sayısı")
plt.show()