# -*- coding: utf-8 -*-
"""odev3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdEZDLn_Z6U_4Smry0dqPk8qZRLj84Kl
"""

import cv2
import numpy as np
from google.colab import files
from matplotlib import pyplot as plt



# Goruntuyu okuma
resim = cv2.imread("pirinc.jpg")

# Gri tonlamaya cevir
gri = cv2.cvtColor(resim, cv2.COLOR_BGR2GRAY)

# Gaussian bulanıklastırma
bulanık_resim = cv2.GaussianBlur(gri, (15, 15), 0)

# Kenarları belirle
kenar = cv2.Canny(bulanık_resim, 30, 110)

# Konturları bul
contours, _ = cv2.findContours(kenar, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Pirinç taneleri icin sayac
sayac = 0

for contour in contours:
    alan = cv2.contourArea(contour)
    if alan > 100:
        sayac += 1


print("Pirinç taneleri sayısı:",sayac)


plt.imshow(resim)

plt.show()